# Generated by Django 3.2.3 on 2021-05-18 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Приоритет')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('will_end', models.DateTimeField(verbose_name='Дата выполнения')),
                ('name', models.CharField(max_length=250, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='описание')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.priority', verbose_name='Приоритет')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
